apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-environment-secret
  labels:
    {{- include "vpw-pipeline-chart.labels" . | nindent 4 }}
data:
  ELASTIC_PWD: {{ .Values.environment.secret.elastic_pwd | b64enc | quote }}