apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.volumes.basicAuthVolume.secretName }}
  labels:
    {{- include "vpw-frontend-chart.labels" . | nindent 4 }}
data:
  htpasswd: {{ .Values.volumes.basicAuthVolume.htpasswd }}