apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-environment-secret
  labels:
    {{- include "vpw-analyzer-chart.labels" . | nindent 4 }}
data:
  POSTGRESQL_PWD: {{ .Values.environment.secret.postgresql_pwd | quote }}
  ELASTIC_PWD: {{ .Values.environment.secret.elastic_pwd | b64enc | quote }}
  ELASTIC_USERNAME: {{ .Values.environment.secret.elastic_username | b64enc | quote }}
