apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-environment-secret
  labels:
  {{- include "vpw-polling-client-chart.labels" . | nindent 4 }}
data:
  CAMUNDA_REST_PASSWORD: {{ .Values.environment.secret.camundaPassword | b64enc | quote}}

